autocmd FileType python set complete+=k~/.vim/syntax/python.vim isk+=.,(

filetype on
filetype plugin on
filetype indent on

syntax enable
set background=dark
colorscheme solarized

set tags=~/tmp/tags

"Set the leader and change exit from esc to jj 
let mapleader = ","
inoremap jj <ESC>

set wildignore+=*/tmp/*,*.so,*.swp,*.zip     " MacOSX/Linux

"removing trailing white space
autocmd BufWritePre *.rb :%s/\s\+$//e

"rails vim
":Rfac item
autocmd User Rails Rnavcommand factory    spec/factories   -suffix=_factory.rb

set backspace=indent,eol,start
set nocompatible
set ignorecase
set autoindent
set smartcase
set viminfo='10,\"100,:20,%,n~/.viminfo
set textwidth=80
set tabstop=4
set shiftwidth=4
set softtabstop=4


map <C-n> :NERDTreeToggle<CR>
map ] :NERDTreeFind<CR>

autocmd BufNewFile,BufRead *.py set ft=python
autocmd BufNewFile,BufRead *.rb set ft=ruby
autocmd BufNewFile,BufRead *.js set ft=javascript
autocmd BufNewFile,BufRead *.json set ft=javascript

au! BufRead,BufNewFile *.json setfiletype json 
au! BufRead,BufNewFile *.scala setfiletype scala
au! BufRead,BufNewFile *.py setfiletype python
au! BufRead,BufNewFile *.c setfiletype c

au BufRead,BufNewFile *py,*pyw,*.c,*.h set tabstop=4
au BufRead,BufNewFile *.py,*pyw set shiftwidth=4
au BufRead,BufNewFile *.js,*.rb set shiftwidth=2
au BufRead,BufNewFile *.js,*.rb,*.rake set shiftwidth=2
au BufRead,BufNewFile *.js,*.rb,*.rake set tabstop=2
au BufRead,BufNewFile *.js,*.rb,*.rake set softtabstop=2
au BufRead,BufNewFile *.py,*.pyw,*.rb,*.js set expandtab

autocmd BufWritePre *.py normal m`:%s/\s\+$//e ``

set statusline=%<\ %n:%f\ %m%r%y%=%-35.(line:\ %l\ of\ %L,\ col:\ %c%V\ (%P)%)
set laststatus=2

nnoremap ; :

nnoremap <C-p> :FuzzyOpen<CR>
nnoremap <C-g> :FuzzyGrep<CR>

if executable('ag')
  let g:ackprg = 'ag --vimgrep'
endif

" or
autocmd FileType javascript noremap <buffer>  <c-f> :call JsBeautify()<cr>
" for html
autocmd FileType html noremap <buffer> <c-f> :call HtmlBeautify()<cr>
" for css or scss
autocmd FileType css noremap <buffer> <c-f> :call CSSBeautify()<cr>

"reformats and saves json file if you have json_reformat installed
map <leader>r <Esc>:%!json_reformat <CR>

"Disable the arrows to force me to learn
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
nnoremap j gj
nnoremap k gk
nnoremap t l
xnoremap t l

"Saving and quiting short-cuts
nnoremap <leader>w :w<CR>
nnoremap <leader>wq :wq<CR>
nnoremap <leader>q :q<CR>
nnoremap <leader>qq :q!<CR>

nnoremap <leader>p :set paste<CR>
nnoremap <leader>np :set nopaste<CR>

"hl search highlights as you search
set hlsearch
nnoremap <leader>k :nohlsearch<CR>

nnoremap <leader>c <leader>c<space>

" Folding set up 
set foldmethod=indent
set nofoldenable
nnoremap <leader>l zR
nnoremap <leader>m zM

" Execute file being edited with <Shift> + e:
nnoremap <S-e> :w<CR>:!/opt/py27/bin/python %:p
nnoremap <S-e>v :w<CR>:!/opt/py27/bin/python %:p --verbose

nnoremap <leader>a :Ack

"Easier splits navigation - Remapped Caps Lock to Control
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l
nnoremap <C-t> <C-w>l
nnoremap <leader>v <C-w>v<C-w>l
nnoremap <leader>d <C-w>-
nnoremap <leader>< <C-w><
nnoremap <leader>> <C-w>>
nnoremap <leader>k <C-w>+
nnoremap <leader>h :split<CR>
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
